---
permalink: administration/reference_snap_creator_terminology.html 
sidebar: sidebar 
keywords: snap, creator, terminology,action, backup, lun, clone, volume, agent, monitor, archive, log, configuration, discover, global, job, mount, ossv, profile, policy, quiesce, restore, scdump, schedule, umount, unquiesce, watchdog 
summary: Snap Creator 由几种不同的构造组成，了解语言和概念非常重要。 
---
= Snap Creator 术语
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator 由几种不同的构造组成，了解语言和概念非常重要。

* * 操作 *
+
Snap Creator 可以对配置文件执行各种操作。这通常是一个定义的工作流，用于实现所需的结果。要执行操作，请从 GUI 中选择配置文件，单击 * 操作 * ，然后从下拉列表中选择以下操作之一：

+
** * 备份 *
+
备份配置文件中指定的环境。备份工作流是一个多步骤操作，根据选定配置文件的设置进行更改。配置了插件的备份操作示例可能包括：暂停应用程序或数据库，为所有已定义的卷创建 Snapshot 副本，使选定应用程序或数据库处于静默状态，执行 SnapVault 和 / 或 SnapMirror 更新，对任何保留策略执行操作或对任何归档日志设置执行操作。

** * LUN 克隆 *
+
为 LUN 创建新的 Snapshot 副本并克隆新的 Snapshot 副本。

** * 卷克隆 *
+
为卷创建新的 Snapshot 副本并克隆新的 Snapshot 副本。



* * 代理监控 *
+
代理监控器会向 Snap Creator 服务器查询配置文件中定义的所有代理，并查询这些代理以检查其状态。代理监控器将报告代理是否正在运行，代理正在侦听的端口以及代理正在使用的版本。

* * 归档日志 *
+
归档日志操作可对配置文件的归档日志管理设置中的任何设置执行。此操作通常会清除 Snap Creator 不再需要的日志。

* * 配置文件 *
+
配置文件是 Snap Creator 的核心。它可以配置 Snap Creator ，运行应用程序插件，设置必要的变量，并定义在 Snapshot 副本中捕获的卷。配置文件由不同的参数组成，这些参数可以设置为影响 Snap Creator 的行为。配置文件通常缩短为配置或配置。

* * 发现 *
+
发现操作会对配置文件中详细介绍的环境执行存储级别发现。并非所有插件都支持发现。

* * 全局配置文件 *
+
一种可在超全局级别（参数将影响整个 Snap Creator 服务器环境中的所有配置文件）或配置文件级别（参数将影响指定配置文件中的所有配置文件）下运行的配置文件。超全局参数将使用配置文件级别全局中指定的任何参数进行覆盖。同样，在配置文件中指定的参数将覆盖超级或配置文件级别全局配置文件中的任何参数。全局配置文件通常缩短为全局配置。

* * 作业 *
+
Snap Creator 执行的所有操作均视为作业。某些操作可能包含多个作业。Snap Creator 执行的所有作业都将在作业监控器中列出。

* * 作业监控器 *
+
作业监控器是一个易于使用的信息板界面，可用于简单地查看正在运行或先前已运行的 Snap Creator 作业的状态。作业监控器在设置时已启用，可以存储 1 到 1 ， 000 个作业。

* * 挂载 *
+
通过挂载操作，您可以指定要克隆和挂载的现有 Snapshot 副本。

* * OSSV*
+
OSSV （ Open Systems SnapVault ）操作用于执行 OSSV 操作。

* * 配置文件 *
+
配置文件实际上是一个用于组织配置文件的文件夹。配置文件还充当基于角色的访问控制（ Role-Based Access Control ， RBAC ）的对象，这意味着您只能访问其中包含的特定配置文件和配置文件。

* * 策略 *
+
策略是保留策略的缩写。策略通常会定义 Snapshot 保留策略（要保留的 Snapshot 副本数）和期限（删除 Snapshot 副本之前应保留多长时间）。例如，每日策略可能会保留至少 30 天前的 30 天` ' 的 Snapshot 副本。（保留期限设置可防止在同一天创建的多个 Snapshot 副本绕过可能表示 Snapshot 副本需要使用 30 天的 SLA 。） 如果使用 SnapVault ，则该策略还会为 SnapVault 副本定义任何保留设置。目前，策略可以直接存储在配置文件中，也可以作为策略对象的一部分存储。如果某个策略是配置文件的一部分，则该策略可能称为本地保留策略。

* * 策略对象 *
+
策略对象是可在配置文件级别应用的保留策略。与策略一样，策略对象定义保留策略，但也可以定义计划和标签。以下是策略对象的组成部分：

+
** * 备份类型 *
+
备份类型是可由策略对象设置的标签。

** * 策略分配 *
+
策略分配会为配置文件的特定配置文件分配一个策略（在策略管理中创建）。

** * 策略管理 *
+
策略管理会在策略对象中创建一个策略。这样可以定义 Snapshot 副本的保留计数和保留期限。如果使用 SnapVault ，则还可以设置关联的保留计数和期限。策略管理还允许选择策略计划和备份类型。

** * 策略计划 *
+
策略计划用于定义要对指定计划执行的操作。



* * 暂停 *
+
暂停操作将执行必要的操作，以便将应用程序或数据库置于一致状态。尽管此操作名为 quiesce ，但根据插件或配置文件设置，此操作可能不是真正的暂停操作。例如， Domino 插件执行 Domino API 调用以将 Domino 数据库置于备份启动状态，而 DB2 插件则执行 DB2 write suspend 命令。

* * 还原 *
+
还原操作会对配置文件中指定的一个或多个卷执行卷或单文件还原操作。根据配置文件中使用的插件，可能会有其他还原操作。

* * scdump*
+
scdump 是一种故障排除操作，用于收集配置文件级别的所有配置文件和日志文件，以及一些标准 Snap Creator Server 日志和环境信息。所有这些收集的文件都会压缩到一个 zip 文件中，系统会提示您下载该文件。然后，可以通过电子邮件将 scdump zip 文件发送或上传到支持部门进行分析。

* * 计划 *
+
Snap Creator 服务器包含一个集中式计划程序。这样可以通过策略计划（策略对象的一部分）或通过计划程序直接创建 Snap Creator 作业。计划程序可同时运行多达 10 个作业，并将其他作业排队，直到正在运行的作业完成为止。

* * Snap Creator 代理 *
+
Snap Creator 代理通常与安装应用程序或数据库的主机安装在同一台主机上。代理是插件所在位置。有时，在 Snap Creator 中，此代理会缩短为 scAgent 。

* * Snap Creator Framework *
+
Snap Creator 是一个框架，完整的产品名称为 NetApp Snap Creator Framework 。

* * Snap Creator 插件 *
+
插件用于将应用程序或数据库置于一致状态。Snap Creator 包含多个插件，这些插件已包含在二进制文件中，不需要进行任何其他安装。

* * Snap Creator 服务器 *
+
Snap Creator 服务器通常安装在物理或虚拟主机上。该服务器托管 Snap Creator GUI 和必要的数据库，用于存储有关作业，计划，用户，角色，配置文件， 配置文件和插件中的元数据。在 Snap Creator 中，此服务器有时会缩短为 scServer 。

* * umount*
+
使用 umount 操作可以指定要卸载的现有挂载点。

* * 退出静默 *
+
取消静默操作将执行必要的操作，以使应用程序或数据库返回到正常操作模式。尽管此操作名为 unquiesce ，但根据插件或配置文件设置，此操作可能不是真正的 unquiesce 操作。例如， Domino 插件执行 Domino API 调用以将 Domino 数据库置于备份停止状态，而 DB2 插件则执行 write resume 命令。

* * 监视程序 *
+
watchdog 是 Snap Creator Agent 的一部分，用于监控代理正在执行的作业的状态。如果代理未在指定时间内做出响应，则 watchdog 可以重新启动代理或结束特定操作。例如，如果暂停操作超过超时值，则 watchdog 可以停止暂停操作并启动取消暂停，以使数据库返回到正常运行模式。


