---
permalink: administration/reference_snap_creator_cli_commands_for_workflow_actions.html 
sidebar: sidebar 
keywords: command-line, interface, cli, snap, creator, workflow, command, backup, copy 
summary: 您可以使用命令行界面（ CLI ）命令执行基于图形用户界面（ GUI ）的各种 Snap Creator 工作流操作。 
---
= 用于执行工作流操作的 Snap Creator CLI 命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用命令行界面（ CLI ）命令执行基于图形用户界面（ GUI ）的各种 Snap Creator 工作流操作。

下表提供了用于执行基于 Snap Creator GUI 的工作流操作的命令行界面命令：

|===
| 工作流区域 | 操作 / 说明 | 命令和关联参数 


 a| 
备份
 a| 
创建备份副本。根据与配置文件关联的配置文件执行备份操作。
 a| 
[listing]
----

                  snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backup
--policy Policy
--verbose
----


 a| 
创建 Open Systems SnapVault 备份。使用 Open Systems SnapVault 执行备份操作。这需要 Snap Creator 代理。Snap Creator 服务器与 Snap Creator 代理进行通信并执行 SnapVault 更新。不会创建主备份副本。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action ossv
--policy Policy
--verbose
---- a| 
备份（续 ... ）



 a| 
删除备份副本（手动）。手动删除现有备份。此操作由菜单驱动。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupDel
--policy Policy
--verbose
---- a| 
删除备份副本（自动）。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupDel
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
---- a| 
列出备份副本。列出主存储系统和二级存储系统上的 Snap Creator 备份副本。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupList
--policy Policy
--verbose
----


 a| 
挂载备份副本。对现有备份执行挂载操作。根据备份创建卷克隆，并使用 mount_CMD 命令通过 Snap Creator Agent 挂载此克隆。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action mount
--backupName name
--verbose
---- a| 
备份（续 ... ）



 a| 
卸载备份副本。对现有备份执行卸载操作。根据备份删除卷克隆，并使用 umount_cmds 命令通过 Snap Creator Agent 卸载此克隆。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action umount
--backupName name
--verbose
---- a| 
备份类型



 a| 
创建新的备份类型。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeAdd
--backupTypeName name
--verbose
---- a| 
更新现有备份类型。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeUpdate
--backupTypeId 1
--backupTypeName name
--verbose
---- a| 
删除现有备份类型。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeDelete
--backupTypeId 1

--verbose
----


 a| 
列出备份类型。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeList
--verbose
---- a| 
克隆



 a| 
克隆 LUN 。备份主存储系统，然后使用 LUN 克隆克隆备份。此外，还会处理 igroup 的卷映射。这需要 SAN 或 Isan 环境。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneLun
--policy Policy
--verbose
---- a| 
克隆卷。备份主存储系统，然后使用卷克隆克隆备份。此外，还会处理 igroup ， NFS 或 CIFS 的卷映射。这需要 SAN ， Isan 或 NAS 环境。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneVol
--policy Policy
--verbose
---- a| 
删除克隆。根据指定的保留策略执行克隆删除操作。此 LUN 克隆仅保留一个副本。卷克隆具有与策略关联的使用情况。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneDel
--policy Policy
--verbose
----


 a| 
列出 Snap Creator 克隆。列出给定配置的 Snap Creator 卷克隆。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneList
--verbose
---- a| 
列出 Snap Creator 卷。列出主存储系统上指定配置的 Snap Creator 卷。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action volumeList
--verbose
---- a| 
配置文件
 a| 
导入配置。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action configImport
--importFile file_path
--verbose
---- a| 
导出配置。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action configExport
--exportFile file_path
--verbose
----


 a| 
导入全局配置文件。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalImport
--importFile file_path
--verbose
---- a| 
导出全局配置文件。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalExport
--ExportFile file_path
--verbose
---- a| 
从存储库中删除全局配置文件。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalDelete
--verbose
----


 a| 
配置文件（续 ... ）
 a| 
将特定配置文件的全局配置文件导入到存储库中。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalImport
--importFile file_path
--verbose
----


 a| 
从存储库中导出特定配置文件的全局配置文件。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalExport
--exportFile file_path
--verbose
---- a| 
从存储库中删除特定配置文件的全局配置。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalDelete
--verbose
---- a| 
升级配置文件中的旧配置文件。将新引入的参数添加到旧配置文件中。执行此命令之前，必须将所有旧配置文件以及配置文件文件夹复制到 scServer/enginer/configs 文件夹。
 a| 
[listing]
----
snapcreator
--server IP
--port port
--user userid
--passwd password
--upgradeConfigs
--profile profile_name
--verbose
----


 a| 
作业
 a| 
列出所有作业及其状态。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action jobStatus
--verbose
----


 a| 
策略
 a| 
添加新的本地策略。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType local
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
----


 a| 
策略（续 ... ）
 a| 
添加新的 SnapMirror 策略。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType snapmirror
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
----


 a| 
添加新的 SnapVault 策略。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType snapvault
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--secondaryCount 30
--secondaryAge 0
--verbose
---- a| 
更新 SnapMirror 策略。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyUpdate
--policyId 1
--schedId 1
--backupTypeId 1
--policyType snapmirror
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
---- a| 
策略（续 ... ）
 a| 
更新 SnapVault 策略。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyUpdate
--policyId 1
--schedId 1
--backupTypeId 1
--policyType snapvault
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--secondaryCount 30
--secondaryAge 0
--verbose
---- a| 
删除策略。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyDelete
--policyId 1
--verbose
----


 a| 
列出所有策略。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyList
--verbose
---- a| 
显示特定策略的其他详细信息。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyDetails
--policyId 1
--verbose
---- a| 
为配置文件分配策略。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyAssignToProfile
--policies testPolicy
--verbose
----


 a| 
策略（续 ... ）
 a| 
撤消配置文件的策略分配。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyUnassignFromProfile
--verbose
----


 a| 
列出分配给配置文件的所有策略。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyListForProfile
--verbose
---- a| 
策略计划



 a| 
创建每小时策略计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--verbose
---- a| 
创建每日策略计划。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
策略计划（续 ... ）
 a| 
创建每周策略计划。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
创建 cron 策略计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron '0 0/5 14,18 * * ?'
--schedActive true
--verbose
----


 a| 
更新每小时策略计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--verbose
---- a| 
策略计划（续 ... ）



 a| 
更新每日策略计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
更新每周策略计划。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
更新 cron 策略计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron '0 0/5 14,18 * * ?'
--schedActive true
--verbose
----


 a| 
策略计划（续 ... ）
 a| 
删除策略计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedDelete
--schedId 1
--verbose
----


 a| 
列出策略计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedList
--verbose
---- a| 
显示有关策略计划的追加信息。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedDetails
--schedId 1
--verbose
---- a| 
配置文件
 a| 
创建新配置文件。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileCreate
--verbose
---- a| 
删除配置文件。 * 注意： * 配置文件中的配置文件也会被删除。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileDelete
--verbose
----


 a| 
还原
 a| 
执行交互式还原。对给定策略执行交互式文件还原操作或交互式卷还原操作。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
----


 a| 
执行非交互式卷还原。执行非交互式卷还原。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
---- a| 
执行非交互式文件还原。执行非交互式文件还原。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
--files file_path1,file_path2,etc.
---- a| 
Schedules
 a| 
创建新的每小时计划。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
创建新的每日计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
----


 a| 
创建新的每周计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
计划（续 ... ）



 a| 
创建新的 cron 计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron "0 0/5 14,18 * * ?"
--schedActive true
--schedStartDate date
--verbose
---- a| 
运行计划。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedRun
--schedId 1
--verbose
---- a| 
删除计划
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedDelete
--schedId 10
--verbose
----


 a| 
更新每小时计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName HourlyBackup
--schedFreqId 2
--schedId 1
--schedActionId 1
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
计划（续 ... ）



 a| 
更新每日计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName DailyBackup
--schedFreqId 3
--schedId 1
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
更新每周计划。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName WeeklyBackup
--schedFreqId 4
--schedId 1
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
更新 cron 计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName CronBackup
--schedFreqId 5
--schedId 1
--schedActionId 1
--schedCron "0 0/5 14,18 * * ?"
--schedActive true
--schedStartDate date
--verbose
----


 a| 
计划（续 ... ）
 a| 
列出所有计划。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedList
--verbose
----


 a| 
列出支持的计划程序操作。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedActionList
--verbose
---- a| 
列出支持的计划程序频率。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedFreqList
--verbose
---- a| 
显示计划 ID 的其他详细信息。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedDetails
--schedId 1
--verbose
----


 a| 
scdump
 a| 
在 Snap Creator 根目录下名为 scdump 的 .zip 文件中创建有关特定配置文件的 scdump 日志，配置文件和支持信息。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
-- profile Profile
--config Config
--action scdump
--policy Policy
--verbose
----


 a| 
Snap Creator 服务器和代理
 a| 
列出 Snap Creator 服务器已知的所有代理的状态。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action agentStatus
--verbose
----


 a| 
Snap Creator 服务器和代理（续 ... ）
 a| 
对 Snap Creator 服务器执行 Ping 操作。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action pingServer
--verbose
----


 a| 
对 Snap Creator 代理执行 Ping 操作。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action pingAgent
--agentName host_name
--agentPort port
--verbose
---- a| 
归档



 a| 
根据配置文件中的设置执行归档日志管理。此操作需要 Snap Creator 代理。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action arch
--verbose
---- a| 
数据保护功能



 a| 
为给定配置配置配置 NetApp 管理控制台数据保护功能数据集。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action pmsetup
--verbose
---- a| 
显示控制器的 SnapVault 和 SnapMirror 关系的数据保护状态。如果未配置 SnapVault 或 SnapMirror ，则不会显示结果。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action dpstatus
--verbose
---- a| 
暂停 / 取消静默
 a| 
对给定应用程序执行暂停操作。此操作需要 Snap Creator 代理。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action quiesce
--verbose
---- a| 
对给定应用程序执行取消静默操作。此操作需要 Snap Creator 代理。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action unquiesce
--verbose
----


 a| 
发现
 a| 
对给定应用程序执行发现。此操作需要 Snap Creator 代理。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action discover
--verbose
----
|===