---
permalink: administration/reference_parameters_to_set_up_cloning.html 
sidebar: sidebar 
keywords: parameter, snap, creator, server, cloning, operation 
summary: 要设置 Snap Creator 服务器克隆操作，需要使用多个参数。 
---
= 用于设置克隆操作的参数
:icons: font
:imagesdir: ../media/


[role="lead"]
要设置 Snap Creator 服务器克隆操作，需要使用多个参数。

|===
| 参数 | 正在设置 ... | Description 


 a| 
NTAP_VOL_clone_reserve
 a| 
无
| 文件 


| volume  a| 
这是克隆卷的空间保证。
 a| 
ntap_lun_clone_reservation



 a| 
true
| false  a| 
如果设置为 true ，则在选择 cloneLun 操作时，会为克隆的 LUN 预留空间。否则，不会预留空间。



 a| 
ntap_clone_igroup_map
 a| 
 a| 
指定存储系统，源卷和 igroup 。然后， igroup 会映射到源卷中的克隆 LUN 或卷克隆中的克隆 LUN （例如， `controller1 ： src_volume1/igroup1 ， src_volum2/igroup1 ， src_volume3/igroup1 ； controller2 ： src_volum1/igroup2 ， src_vol2` ， src_igroup2 ， src_vol2 ， src_igroup2 ）。* 注： *

* LUN 克隆的名称与其父卷或父 LUN 相同，并以 _clone 结尾；也就是说，如果卷名为 myvol ，则克隆将为 myvol_clone 。
* 卷克隆以 cl_ 开头，以 -YYYYMMDDHMMSS. 结尾。




 a| 
ntap_clone_for_backup
 a| 
Y
| 不包括 


 a| 
如果启用此选项，则会创建克隆（卷和 LUN ），然后在其他操作完成后将其删除。否则，克隆将在操作完成之前被删除。* 注： * 如果要将克隆备份到磁带，则应将其设置为 Y如果正在执行数据库刷新，则应将其设置为 N
 a| 
ntap_clone_secondary
 a| 
Y



| 不包括  a| 
如果启用此选项，则在 SnapMirror 更新完成后，将在 SnapMirror 目标上创建克隆。* 注： * 此设置应与 NTAP_snapmirror_use_snapshot ， NTAP_snapmirror_wait 和 NTAP_clone_secondary 卷以及 cloneVol 操作结合使用。
 a| 
ntap_clone_secondary 卷



 a| 
 a| 
这是主存储系统或二级存储系统与二级卷的映射。要使 Snap Creator 能够找到二级卷（例如， controller1 ： controller1-sec/vol1 ； controller1 ： controller1-sec/vol2 ），必须执行此操作。
 a| 
NTAP_NUM_VOL_CLEN克 隆



 a| 
 a| 
这是要保留的卷克隆的数量。这与 Snapshot 副本保留策略类似。* 注： * 此功能仅适用于需要在存储控制器上安装 FlexClone 许可证的卷克隆。
 a| 
ntap_nfs_export_host



 a| 
主机 IP
 a| 
应导出克隆的主机名或 IP 地址。此主机是使用 NFS 挂载克隆卷的主机。
 a| 
ntap_nfs_export_access



 a| 
root
| 读写 | 只读 


 a| 
在 NTAP_NFS_export_host 中指定的主机可接收对克隆卷的访问权限或权限。

* root
+
已授予 root 访问权限。

* 只读
+
授予只读访问权限。

* 读写
+
已授予读 / 写访问权限。


 a| 
ntap_nfs_export_persistent
 a| 
true



| false  a| 
确定 NFS 导出是否持久。如果选择 true ，则会导出克隆卷，并更新存储控制器上的 /etc/exports 文件。
 a| 
ntap_cifs_export_enable



 a| 
Y
| 不包括  a| 
设置以使用 CIFS 共享克隆的卷。

|===