---
permalink: administration/reference_storage_error_messages.html 
sidebar: sidebar 
keywords: storage troubleshoot, error, message 
summary: 与存储相关的错误消息可帮助您对发生的任何问题进行故障排除。 
---
= 存储错误消息
:icons: font
:imagesdir: ../media/


[role="lead"]
与存储相关的错误消息可帮助您对发生的任何问题进行故障排除。

下表列出了错误代码和消息，以及错误的简短问题描述和建议的解决方法。

|===
| 错误代码 | 错误消息 | 说明 / 解决方法 


 a| 
存储 -00001
 a| 
日期格式 "%s" 无效： "%s"
 a| 
Snap Creator 未创建卷克隆，或者附加到克隆名称的时间戳无效。



 a| 
存储 -00002
 a| 
无法检索执行程序
 a| 
未为存储创建执行器。查看日志以了解 NetApp 易管理性错误，这些错误可能会揭示问题的发生原因。



 a| 
存储 -00003
 a| 
无法连接到主机
 a| 
无法访问此主机。确保本地防火墙设置正确，并且主机能够从安装了 Snap Creator Server 的系统执行 ping 操作。



 a| 
存储 -01003
 a| 
创建事件 ID 为 "%s" ，类别为 "%s" ，问题描述为 "%s" ，级别为 "%s" ，主机名为 "%s" 的 AutoSupport 消息失败，并显示错误为 "%s" 。
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -01004
 a| 
对于文件还原，源卷和目标卷必须是同一个卷。
 a| 
源卷和目标卷不同。请提供与源卷和目标卷相同的卷。



 a| 
存储 -02003
 a| 
在卷 "%s" 上创建一致性组 Snapshot 副本 "%s" 失败，并出现错误 "%s" ；
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02006
 a| 
在 CG ID 为 "%s" 的 "%s" 上提交一致性组 Snapshot 副本失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02009
 a| 
在卷 "%s" 上创建 Snapshot 副本 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02015
 a| 
删除卷 "%s" 上的 Snapshot 副本 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02021
 a| 
还原卷 "%s" 的 Snapshot 副本 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02025
 a| 
将文件 "%s" 从 Snapshot 副本 "%s" 还原到 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02028
 a| 
在卷 "%s" 上创建主 SnapVault Snapshot 副本计划 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02034
 a| 
从卷 "%s" 删除主 SnapVault Snapshot 副本计划失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02038
 a| 
基于 Snapshot 副本 "%s" 为卷 "%s" 创建克隆 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02041
 a| 
基于 Snapshot 副本 "%s" 将卷 "%s" 上的文件 "%s" 克隆到 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02043
 a| 
列出路径 "%s" 上的文件失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02046
 a| 
基于具有空间预留的 Snapshot 副本 "%s" 将 LUN "%s" 克隆到 "%s" 失败，并显示错误为 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02049
 a| 
从卷 "%s" 删除 LUN "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02052
 a| 
列出 LUN 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02062
 a| 
为访问权限为 "%s" 的主机名 "%s" 添加 NFS 导出 "%s" 失败，并显示错误为 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02072
 a| 
检索控制器 "%s" 上的 SnapMirror 状态失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02075
 a| 
检索控制器 "%s" 上的 SnapMirror 关系失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02082.
 a| 
基于 Snapshot 副本 "%s" 更新 SnapMirror 关系 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02092
 a| 
在卷 "%s" 上列出 Snapshot 副本失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02102
 a| 
将卷 "%s" 上的 Snapshot 副本 "%s" 重命名为 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02112
 a| 
检索控制器 "%s" 上的 SnapVault 状态失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02115
 a| 
检索控制器 "%s" 上的 SnapVault 关系失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02122
 a| 
基于 Snapshot 副本 "%s" 更新 SnapVault 关系 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02132
 a| 
基于卷 "%s" 列出克隆卷失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02142
 a| 
删除卷 "%s" 失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02152
 a| 
列出卷失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02155
 a| 
列出卷 "%s" 失败，并显示错误消息 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -02162
 a| 
还原卷 "%s" 的 Snapshot 副本 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03001
 a| 
正在从集群模式 ONTAP 节点 "%s" 检索 SVM
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -05003
 a| 
创建 NetApp 管理控制台数据集 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -05006
 a| 
在存储控制器 "%s" 上创建由 NetApp 管理控制台驱动的数据集 "%s" 备份失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -05009
 a| 
检索数据集 "%s" 的 NetApp 管理控制台数据集状态失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -05012
 a| 
验证 NetApp 管理控制台数据集 "%s" 失败，并出现错误 "%s" 。
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -05018
 a| 
正在为 "%s" 创建 OM 事件 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03002
 a| 
在 LUN "%s" 上映射 igroup "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03005
 a| 
在卷 "%s" 上创建 LUN "%s" 失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03008
 a| 
在卷 "%s" 上创建主 SnapVault Snapshot 副本 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03011
 a| 
列出数据集 "%s" 的 NetApp 管理控制台备份副本失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03014
 a| 
删除 NetApp 管理控制台备份版本 ID "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03019
 a| 
为 "%s" （ "%s" ）启动 NetApp 管理控制台备份失败，正在退出！
 a| 
检查日志中的错误。您很可能遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03022
 a| 
作业 ID 为 "%s" 的 NetApp 管理控制台备份进度启动失败，正在退出！
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03025
 a| 
删除路径 "%s" 上的文件失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03030
 a| 
发现 "%s" 上的集群模式 Data ONTAP 节点失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03033
 a| 
获取系统版本详细信息 "%s" 失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03036
 a| 
在路径 "%s" 上创建目录失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03039
 a| 
删除路径 "%s" 上的目录失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03043
 a| 
在路径 "%s" 上创建文件失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03046
 a| 
修改数据集 "%s" 的 NetApp 管理控制台数据集失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03049
 a| 
无法读取文件 "%s" 的文件内容
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03052
 a| 
选项 "%s" 的选项获取失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03055
 a| 
对象 "%s" 的性能计数器获取失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03058
 a| 
对象 "%s" 的性能实例获取失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03061
 a| 
为 "%s" 提供的 NetApp 管理控制台数据集信息失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03064
 a| 
系统命令行界面命令 "%s" 失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03067
 a| 
删除 NetApp 管理控制台数据集 "%s" 失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03070
 a| 
基于 Snapshot 副本 "%s" 还原 SnapVault 关系 "%s" 失败，并出现错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03073
 a| 
为以下项导出 CIFS 失败： "%s" ！
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03076
 a| 
获取控制器 "%s" 上的根卷失败，并显示错误 "%s"
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03079
 a| 
卷 "%s" 的接合路径获取失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03082
 a| 
系统名称获取失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03085
 a| 
控制器 "%s" 上的 NFS 服务获取失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03088
 a| 
主机 "%s" 路径名称 "%s" 权限 "%s" 的 NFS 权限检查失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03091
 a| 
控制器 "%s" 上的网络接口获取失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。



 a| 
存储 -03094
 a| 
卷 "%s" 上的 qtree 列表失败
 a| 
检查日志中的错误。您很可能会遇到 NetApp 易管理性错误。这些日志可能会显示此问题的发生原因。

|===