---
permalink: administration/reference_repository_error_messages.html 
sidebar: sidebar 
keywords: table, repository, error, message, global, configuration, repo 
summary: 下表列出了存储库错误消息。 
---
= 存储库错误消息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下表列出了存储库错误消息。

|===
| 错误代码 | 错误消息 | 说明 / 解决方法 


 a| 
repo-01001.
 a| 
全局配置不存在
 a| 
检查 configs 文件夹中是否存在 global.conf 文件。



 a| 
repo-01002.
 a| 
全局配置已存在
 a| 
configs 文件夹中已存在 global.conf 文件。请先删除全局配置文件或更新现有文件。



 a| 
repo-01103
 a| 
创建全局配置失败，并出现错误 "%s"
 a| 
无法在 configs 文件夹中创建 global.conf 文件。检查运行 Snap Creator 的用户对目录的权限。



 a| 
repo-01203
 a| 
更新全局配置失败，并出现错误 "%s"
 a| 
无法更新 configs 文件夹中的 global.conf 文件。检查运行 Snap Creator 的用户对目录的权限。



 a| 
repo-01303
 a| 
删除全局配置失败，并显示错误 "%s"
 a| 
无法删除 configs 文件夹中的 global.conf 文件。检查文件是否位于 configs 文件夹中，或者检查运行 Snap Creator 的用户对目录的权限



 a| 
repo-01403
 a| 
导出全局配置失败，并出现错误 "%s"
 a| 
无法读取 configs 文件夹中的 global.conf 文件。检查是否已删除全局配置文件。



 a| 
repo-01503
 a| 
导入全局配置 "%s" 失败，并显示错误 "%s"
 a| 
无法更新 configs 文件夹中的 global.conf 文件。检查运行 Snap Creator 的用户对目录的权限。



 a| 
repo-01603
 a| 
检索全局配置失败，并出现错误 "%s"
 a| 
无法读取 configs 文件夹中的 global.conf 文件。检查是否已删除全局配置文件。



 a| 
repo-02002
 a| 
配置文件 "%s" 已存在，请使用其他名称。
 a| 
同名配置文件已存在。如果此配置文件不可见，则用户无权访问此配置文件。



 a| 
repo-02003
 a| 
配置文件 "%s" 不存在
 a| 
检查您的配置文件是否已重命名或删除。此外，用户可能没有此配置文件的权限。



 a| 
repo-02103
 a| 
创建全局配置文件配置 "%s" 失败，并出现错误 "%s"
 a| 
无法在配置文件中创建 global.conf 文件。检查运行 Snap Creator 的用户对目录的权限。



 a| 
repo-02106
 a| 
创建配置文件配置 "%s" 失败，并显示错误 "%s"
 a| 
无法在 configs 文件夹中创建配置文件。检查运行 Snap Creator 的用户对目录的权限。



 a| 
repo-02203
 a| 
更新配置文件配置 "%s" 失败，并显示错误 "%s"
 a| 
无法更新 configs 文件夹中的配置文件。检查运行 Snap Creator 的用户对目录的权限。



 a| 
repo-02213
 a| 
将配置文件 "%s" 重命名为 "%s" 失败，并出现错误 "%s"
 a| 
无法重命名 configs 文件夹中的配置文件。检查运行 Snap Creator 的用户对目录的权限，或者检查您的配置文件是否已重命名或删除。



 a| 
repo-02303
 a| 
删除配置文件配置 "%s" 失败
 a| 



 a| 
repo-02403
 a| 
导出配置文件配置 "%s" 失败，并显示错误 "%s"
 a| 



 a| 
repo-02503
 a| 
导入配置文件配置 "%s" 失败，并显示错误 "%s"
 a| 



 a| 
repo-02603
 a| 
检索全局配置文件失败，并出现错误 "%s"
 a| 



 a| 
repo-02606
 a| 
检索配置文件 "%s" 失败，并出现错误 "%s"
 a| 



 a| 
repo-02703
 a| 
列出配置文件失败，并出现错误 "%s"
 a| 
列出配置文件失败。检查 configs 文件夹路径。



 a| 
repo-03002
 a| 
配置文件 "%s" 已存在配置 "%s"
 a| 
给定配置文件已存在同名配置文件。请选择其他名称。



 a| 
repo-03103
 a| 
为配置文件 "%s" 创建配置文件 "%s" 失败，并显示错误 "%s"
 a| 



 a| 
repo-03203
 a| 
更新配置文件 "%s" 的配置 "%s" 失败，并出现错误 "%s"
 a| 



 a| 
repo-03212
 a| 
将配置文件 "%s" 的配置 "%s" 重命名为 "%s" 失败
 a| 
无法从配置文件重命名配置。检查您的配置是否已重命名或删除，并检查运行 Snap Creator 的用户对目录的权限。



 a| 
repo-03303
 a| 
从配置文件 "%s" 删除配置文件 "%s" 失败
 a| 
无法从 configs 文件夹中的配置文件中删除配置。检查运行 Snap Creator 的用户对目录的权限。



 a| 
repo-03403
 a| 
导出配置文件 "%s" 的配置 "%s" 失败，并出现错误 "%s"
 a| 



 a| 
repo-03503
 a| 
将配置 "%s" 导入到配置文件 "%s" 失败，并出现错误 "%s"
 a| 



 a| 
repo-03603
 a| 
从配置文件 "%s" 检索配置 "%s" 失败，并出现错误 "%s"
 a| 



 a| 
repo-03703
 a| 
从配置文件 "%s" 列出配置失败，并显示错误 "%s"
 a| 



 a| 
repo-04003
 a| 
读取配置文件 "%s" ，配置 "%s" 和时间戳 "%s" 的目录失败，并出现错误 "%s"
 a| 



 a| 
repo-04103
 a| 
为配置文件 "%s" ，配置 "%s" 和时间戳 "%s" 写入目录失败，并出现错误 "%s"
 a| 



 a| 
repo-04203
 a| 
清除配置文件 "%s" ，配置 "%s" 和时间戳 "%s" 的目录失败，并显示错误 "%s"
 a| 



 a| 
repo-04303
 a| 
配置文件 "%s" 和配置 "%s" 的目录查询失败，并出现错误 "%s"
 a| 



 a| 
repo-04304
 a| 
配置 "%s" 不存在
 a| 



 a| 
repo-04309
 a| 
添加策略对象失败 "%s"
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04313
 a| 
删除策略 ID 为 %s 的策略对象失败
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04315
 a| 
更新策略对象失败： %s
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04316
 a| 
无法列出策略
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04321
 a| 
添加备份类型对象失败 "%s"
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04323
 a| 
备份类型 ID 为 %s 的备份类型条目不存在
 a| 
传递有效的备份类型。



 a| 
repo-04325
 a| 
删除备份类型 ID 为 %s 的备份类型对象失败
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04327
 a| 
更新备份类型对象失败： %s
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04328
 a| 
无法列出备份类型
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04333
 a| 
添加计划程序作业对象失败 "%s"
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04335
 a| 
作业 ID 为 %s 的计划程序作业条目不存在
 a| 
传递有效的计划程序作业。



 a| 
repo-04337
 a| 
删除作业 ID 为 %s 的计划程序作业对象失败
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04339
 a| 
更新计划程序作业对象失败： %s
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04340
 a| 
无法列出计划程序作业
 a| 
数据库错误；有关详细信息，请检查堆栈跟踪。



 a| 
repo-04341
 a| 
添加策略对象失败，已存在同名策略 "%s"
 a| 
同名策略已存在；请尝试使用不同名称。



 a| 
repo-04342
 a| 
添加备份类型对象失败，已存在同名备份类型 "%s"
 a| 
已存在同名备份类型；请尝试使用不同名称。



 a| 
repo-04343
 a| 
添加计划程序对象失败，已存在任务名称相同的计划程序 "%s"
 a| 



 a| 
repo-04344
 a| 
无法更新配置文件 "%s" 。配置文件为空。
 a| 



 a| 
repo-04345
 a| 
添加新策略时，策略类型不能为空
 a| 



 a| 
repo-04346
 a| 
存储对象不能为空
 a| 



 a| 
repo-04347
 a| 
添加存储对象失败，已存在同名 /IP 的存储 "%s"
 a| 



 a| 
repo-04348
 a| 
无法提取存储详细信息。数据库错误！
 a| 



 a| 
repo-04349
 a| 
主机名无效。主机名为 /IP 的存储不存在 "%s"
 a| 



 a| 
repo-04350
 a| 
主机名不能为空
 a| 
主机名无效



 a| 
repo-04451
 a| 
删除存储 "%s" 失败，并显示错误 "%s"
 a| 
无法删除存储。数据库错误！



 a| 
repo-04355
 a| 
更新存储 "%s" 失败，并出现错误 "%s"
 a| 
无法更新存储。数据库错误！



 a| 
repo-04356
 a| 
集群对象不能为空
 a| 



 a| 
repo-04358
 a| 
添加存储失败 "%s" ，并显示错误 "%s"
 a| 



 a| 
repo-04369
 a| 
更新集群 "%s" 失败，并出现错误 "%s"
 a| 



 a| 
repo-04360
 a| 
添加集群对象失败，已存在同名 /IP 的集群 "%s"
 a| 
具有相同主机名的集群已存在

|===