---
permalink: administration/reference_oracle_plug_in.html 
sidebar: sidebar 
keywords: oracle, plug-in, sql, plus, database, quiesce, unquiesce, oracle, database 
summary: Oracle 插件使用 SQL* Plus 与数据库进行通信，并暂停和取消暂停 Oracle 数据库以进行备份。 
---
= Oracle 插件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle 插件使用 SQL* Plus 与数据库进行通信，并暂停和取消暂停 Oracle 数据库以进行备份。

Snap Creator Oracle 插件支持 Oracle 自动存储管理（脱机或联机备份）以及对 Real Application Clusters （ RAC ）数据库配置进行联机备份。互操作性表包含有关支持和兼容性的最新信息。

要在 UNIX 或 Linux 平台上将 C Shell （ CSH ）与 Oracle 插件结合使用，应满足以下条件：

* Snap Creator Agent 必须以 Oracle 用户身份启动，而不是以 root 用户身份启动。
* Oracle 用户必须设置适当的环境变量（ ORACLE_HOME 和 ORACLE_SID ），插件驱动的 SQL* Plus 命令才能正常运行。
+
可以使用 shell 启动文件（例如 ~ /.cshrc ）来完成此操作。



下表列出了 Oracle 插件参数，提供了这些参数的设置并对其进行了说明：

|===
| 参数 | 正在设置 ... | Description 


 a| 
应用程序名称
 a| 
Oracle
 a| 
应用程序名称



 a| 
ORACLE_Databases
 a| 
DB_name ： user_name
 a| 
Oracle 数据库和用户名列表多个数据库和用户名可以指定为分号分隔列表，例如， `dB1 ：用户 1 ； DB2 ：用户 2` 。



 a| 
sqlplus_CMD
 a| 
 a| 
sqlplus 命令的路径



 a| 
CNTL_file_backup_DIR
 a| 
 a| 
用户应存储备份控制文件的目录的路径 Oracle 用户必须对此目录具有适当的权限。



 a| 
ora_临时
 a| 
 a| 
用于存储临时文件的目录的路径，例如 /tmp.The Oracle user must have appropriate permissions to this directory 。



 a| 
archive_log_only
 a| 
Y
| 不包括 


| 策略： <Y | 不包括  a| 
通知 Oracle 插件仅执行交换机日志操作如果要处理归档日志备份而不是数据备份，则此设置非常有用。



 a| 
ORACLE_HOME
 a| 
 a| 
Oracle 主目录的路径



 a| 
ORACLE_HOME_SID
 a| 
 a| 
给定系统标识符（ SID ）的 Oracle 主目录的路径备份多个数据库时，指定多个 Oracle 主目录可能很重要。



 a| 
ORACLE_export_parameters
 a| 
Y
| 不包括 


 a| 
使用 export 命令导出 ORACLE_HOME 和 ORACLE_SID 环境参数。这仅适用于 UNIX 或基于 Linux 的环境。
 a| 
ORACLE_BACKUPMODE
 a| 



 a| 
可选择使用 Snap Creator 策略配置脱机或联机备份。默认选项为联机。ORACLE_BACKUPMODE=hourly ：联机， daily ：脱机
 a| 
ORACLE_SHUTDOWNABORT
 a| 
Y

|===
* 相关信息 *

http://mysupport.netapp.com/matrix["互操作性表工具： mysupport.netapp.com/matrix"]
