---
permalink: administration/task_customizing_the_default_keystore.html 
sidebar: sidebar 
keywords: keystore, certificate, keytool, windows, unix 
summary: 您可以使用 Windows 和 UNIX 上提供的 keytool 命令自定义默认密钥库或证书。 
---
= 自定义默认密钥库
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Windows 和 UNIX 上提供的 keytool 命令自定义默认密钥库或证书。

keytool 命令由 Java 提供。在某些环境中，您可能需要切换到 Java 安装目录才能运行 keytool 命令。

Snap Creator 不支持信任存储库。

. 停止 Snap Creator 代理。
. 使用单个证书生成新的密钥库：
+
`keytool -genkeypair -alias alias_name -keystore keystore_file -keypass private_key_password -storepass keystore_password`

+
keytool -genkeypair -alias servicekey-keystore serviceKeystore.jks -keypass kypswd123 -storepass kystrpswd123

. 将密钥库文件复制到 scAgent4.3.0/etc/ 目录。
. 更新 Snap Creator 代理配置文件（ scAgent4.3.0/etc/allowed_commands.config ）中的 keystore_file=keystore_file 和 keystore_pass=keystore 密码参数。
. 启动 Snap Creator 代理。


* 相关信息 *

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_windows.adoc[在 Windows 上启动，验证和停止 Snap Creator 代理]

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_unix.adoc[在 UNIX 上启动，验证和停止 Snap Creator 代理]
