---
permalink: administration/task_creating_global_configuration_files.html 
sidebar: sidebar 
keywords: global, configuration, storage, controller, file, create, backup, super, profile 
summary: 您可以创建一个全局配置文件，以便将存储控制器， Storage Virtual Machine （ SVM\ ）或 VMware 凭据配置与备份策略分开。 
---
= 正在创建全局配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建一个全局配置文件，以便将存储控制器， Storage Virtual Machine （ SVM ）或 VMware 凭据配置与备份策略分开。

通过全局配置文件，您可以控制访问并处理备份和还原操作。

您可以创建两种类型的全局配置文件：

* * 超级全球 *
+
此配置会对所有配置文件中的所有配置进行适用场景。

* * 配置文件全局 *
+
此配置适用场景配置文件中创建的所有配置。

+
.. 从 Snap Creator 图形用户界面的主菜单中，选择 * 管理 * > * 全局配置 * 。
.. 在全局配置窗格中，单击 * 创建全局 * 。
+
此时将在右侧窗格中打开全局配置的配置向导。

.. 完成配置向导以创建配置文件：
+
... 在 * 配置 * 页面上，选择全局配置类型（超级全局或全局配置文件）。
+
默认情况下，配置文件的名称设置为 global 。您不能更改此名称。

+
如果选择配置文件全局作为全局配置类型，请选择配置文件。

+

NOTE: 默认情况下，密码加密处于启用状态，以防止密码以明文形式显示在配置文件中。

... 在插件类型页面上，选择插件的类型。
+
您在向导中前进到的页面取决于您选择的选项。

+
|===
| 插件类型选项 | 下一页 | 下一页 


 a| 
虚拟化插件
 a| 
* 虚拟化插件 * 选择要配置的插件。
 a| 
* 身份验证信息 * 提供选定插件选项的身份验证信息。



 a| 
无
 a| 
* 存储连接设置 *
 a| 
--

--
|===
+
有关插件凭据的详细信息，请参见插件文档。

... 在存储连接设置页面上，选择传输类型（ HTTP 或 HTTPS ）。
+
此时将显示选定传输类型的标准端口。如果存储系统使用非标准端口，请在端口字段中输入端口信息。

... 在 Controller/Vserver Credentials 页面上，输入包含此配置文件中的卷的每个存储控制器或 SVM 的 IP 地址和登录凭据。
+

NOTE: 必须至少向配置中添加一个存储控制器或 SVM 。要使用vsim通道功能、请选中* IP通道*复选框(仅适用于集群)。

... 在控制器凭据页面上，验证控制器是否显示正确的信息。
+
如果需要更改，请选择一个控制器，然后单击 * 编辑 * 。

... 在 DFM/OnCommand 设置页面上，如果要将 Snap Creator 配置与 NetApp OnCommand 管理工具集成，请选择并提供详细信息。
... 查看摘要，然后单击 * 完成 * 。





