---
permalink: installation/task_installing_the_snap_creator_server_on_unix.html 
sidebar: sidebar 
keywords: installing, install, snap, creator, server, unix, unix-based 
summary: 对于 UNIX 平台（ AIX ， HP-UX ， Linux 和 Solaris ），安装 Snap Creator 的过程包括提取 Snap Creator 软件包（一个包含 Snap Creator 服务器和 Snap Creator 代理的 .tar 文件），运行设置脚本，启动服务以及验证端口。 
---
= 在基于 UNIX 的系统上安装 Snap Creator 服务器
:icons: font
:imagesdir: ../media/


[role="lead"]
对于 UNIX 平台（ AIX ， HP-UX ， Linux 和 Solaris ），安装 Snap Creator 的过程包括提取 Snap Creator 软件包（一个包含 Snap Creator 服务器和 Snap Creator 代理的 .tar 文件），运行设置脚本，启动服务以及验证端口。

必须安装 JRE 1.8 Update 72 或更高版本。

执行安装的人员必须具有足够的访问权限和特权才能执行安装。


NOTE: 要执行初始设置，您必须具有根级别权限。

Snap Creator 服务器的默认端口为 8443 。您可以使用 netstat 或类似工具来验证要使用的网络端口是否支持 HTTPS ，是否可用以及是否尚未使用（例如，在 UNIX 主机上，您可以输入 `netstat -nap | grep 8443` ）。

您必须已下载 Snap Creator 。

UNIX 服务（服务器和代理）功能为 Snap Creator 服务器和 Snap Creator 代理提供了一个启动脚本。这些启动脚本以 UNIX shell 脚本（ Bourne shell 脚本）的形式编写，可在 Snap Creator 支持的所有 UNIX 环境中运行。

. 将下载的 Snap Creatortar.gz 文件复制到要安装 Snap Creator Server 的位置：
+
.. 创建子目录： mkdir snap_creator_directoryCreate a 子目录：
+
mkdir snap_creator_directory

+
[listing]
----
mkdir /SC_41
----
.. 将 Snap Creatortar.gz 文件复制到新创建的目录：
+
[listing]
----
cp NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
/snap_creator_directory
----
+
[listing]
----
cp NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
/SC_41
----


. 更改为 Snap Creator Framework .tar 文件所在的目录，然后提取该文件：
+

NOTE: 根据 UNIX 环境的不同，您可能需要先解压缩文件，然后再输入 tar 命令。

+
[listing]
----
cd snap_creator_directory
tar -xvf NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
----
+
** snap_creator_directory 是安装 Snap Creator 的位置。
** release 是 Snap Creator 软件包的最新版本。
** 操作系统是操作系统。
+
[listing]
----
cd /sc_41
tar -xvf NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
----


+
此操作将同时提取服务器和代理软件。通常，仅配置 Snap Creator 服务器。代理通常位于要保护的数据库或应用程序服务器上，如以下示例所示：

+
+

+
[listing]
----
NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz  scServer4.1.0
scAgent4.1.0
----
. 执行 Snap Creator 的初始设置：
+
[listing]
----
cd scServer*
./snapcreator --setup
Welcome to the NetApp Snap Creator Framework release-version!
\#\#\# Installation options \#\#\#
01. NetApp Snap Creator Framework release-version Server
02. NetApp Snap Creator Framework release-version Remote CLI
Select install option (enter a number or "q" to quit):
----
+
输入 `01` 以安装 Snap Creator 服务器。

+
** 选项 01 通过配置 Snap Creator 用户和密码，指定要运行 Snap Creator 服务器的图形用户界面端口以及配置其他参数来执行 Snap Creator 服务器的初始设置。
** 选项 02 将 Snap Creator 服务器设置为本地二进制文件，并允许您将命令从本地系统命令行界面问题描述到远程 Snap Creator 服务器。


. 在此处输入 y 以接受最终用户许可协议：
+
[listing]
----
END USER LICENSE AGREEMENT
...the EULA displays...

Do you accept the End User License Agreement (y|n): <Enter y>

Enter controller serial number (Recommended): <OPTIONAL: Enter serial number for one of your storage controllers>
----
. 输入控制器序列号。
+
控制器序列号嵌入在 Snap Creator 属性文件中，并包含在支持和日志输出中。您可以使用此信息帮助解决稍后可能发生的任何问题。

. 输入服务器端口，系统 IP 和 Java 文件箱路径，然后按照提示继续操作。
+
[listing]
----
Enter Snap Creator server port [8443]: <Enter server port>

Enable job monitor (Y|N): <Enter Y>

Enter job monitor size, how many jobs to allow [100]: <Enter the number of jobs from 1-1000>
----
+

NOTE: 尽管 * 作业监控器大小 * 的最大可接受值为 10 ， 000 ，但建议的最大大小为 1000 。

+
[listing]
----
Enter scServer Administrator Username: <Enter the Administrator username>
Enter password for snap_creator_administrator: <Enter the password>
Confirm password for snap_creator_administrator: <Enter the password again>

Enter JAVA Bin Path: /usr/java/default/bin
Enter Your System IP: 10.232.30.18
INFO: Updated NetApp Snap Creator Framework release-version
/install_path/scServerrelease-version/engine/etc/snapcreator.properties
INFO: Updated NetApp Snap Creator Framework release-version
/install_path/scServerrelease-version/bin/scServer

INFO: To start scServer please do the following:

/install_path/scServerrelease-version/bin/scServer start

INFO: To access NetApp Snap Creator Framework release-version GUI goto https://hostname:gui_port
----
. 启动 Snap Creator Framework 服务器：
+
[listing]
----
/install_path/scServerrelease-version/bin/scServer start
Checking Status of scServer:
Running
----
. 导航到指定端口上的本地主机（例如 https://10.12.123.123:8443)[]。
+
您必须使用 HTTPS 进行连接；否则，图形用户界面将不起作用。

+
如果通信通过防火墙，请打开网络端口。



* 相关信息 *

xref:task_installing_java_on_snap_creator_hosts.adoc[在 Snap Creator 主机上安装 Java]

xref:task_downloading_the_snap_creator_software.adoc[下载 Snap Creator 软件]
