---
permalink: installation/task_upgrading_the_snap_creator_agent_3_6_x_on_unix.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, agent, 3.6.x, unix 
summary: 您可以直接从 UNIX 上的 Snap Creator Agent 3.6.x 进行升级。 
---
= 在 UNIX 上升级 Snap Creator Agent 3.6.x
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以直接从 UNIX 上的 Snap Creator Agent 3.6.x 进行升级。

* 在备份 Snap Creator Agent 目录之前，您已停止 Snap Creator Agent ，以确保备份的数据完整。
+
例如，输入以下命令：

+
[listing]
----
/install_path/scAgent3.6.x/bin/scAgent stop
----
* 您已在 Snap Creator Agent 目录（ /install_path/scAgent3.6.x ）中备份以下目录以及所有关联的子目录和文件：
+
** agent.conf 文件（ ./config/agent.conf ）
** 日志目录（如果已启用）（ ./logs ）
** 插件目录（ ./plugins ）




4.1 之前版本中的 Snap Creator Agent 使用名为 agent.conf 的文件列出了 Snap Creator 之外可以在 Snap Creator 代理上执行的命令。在 4.1 中，使用 allowed_commands.config 文件。

同样， agent.conf 文件也会列出允许 Snap Creator Agent 与之通信的主机。默认情况下， Snap Creator 代理允许与所有 Snap Creator 服务器进行通信。但是，如果您选择在先前版本的 Snap Creator 中使用此功能，则 agent.properties 文件中的 authorized_hosts 参数现在将替换该功能。


NOTE: 如果未使用这些参数，只需简单安装新代理即可。

以下步骤中提供的路径是指默认安装路径。以下命令中的路径可能与安装路径中的路径不同。

. 如果尚未停止 Snap Creator Agent ，请停止此操作。
+
有关信息，请参见本主题前面提供的详细信息。

. 安装最新的 Snap Creator 代理，但不要启动 Snap Creator 代理。
+
有关详细信息，请参见有关在 UNIX 上安装 Snap Creator Agent 的信息。

. 在文本编辑器中打开 agent.conf 文件的备份副本。
+
以下是 agent.conf 的示例：

+
[listing]
----
host: scServer@Lyon
command: rc_domino
----
. 在文本编辑器中打开新的 allowed_commands.config 文件（ /install_path/scAgent4.1.x/etc/allowed_commands.config ），然后将命令行从 agent.conf 复制到 allowed_commands.config 文件中；但是，由于最新的 Snap Creator 中的安全性增强，请确保命令完全符合要求。
+
从上一示例中， allowed_commands.config 文件应包含以下内容：

+
[listing]
----
command: /etc/init.d/rc_domino
----
+

NOTE: 如果命令包含任何空格，则必须将命令封装在引号内。

+
您可以根据需要添加命令，每个命令位于单独的行上。

+
进行更改后保存并关闭文件。

. 在文本编辑器中打开 agent.properties 文件（ /install_path/scAgent4.1.x/etc/agent.properties ），并更改 Authorized_hosts=* 的默认条目以反映 agent.conf 文件中的主机设置，然后保存并关闭该文件。
+
在上一示例中， authorized_hosts 参数应包含以下内容：

+
[listing]
----
AUTHORIZED_HOSTS=Lyon
----
+
可以根据需要添加主机，使用逗号分隔主机名。主机名和 IP 地址均受支持：

+
[listing]
----
AUTHORIZED_HOSTS=Lyon, 10.10.10.192, Fuji01
----
. 输入以下命令启动 Snap Creator Agent ：
+
[listing]
----
/install_path/scAgent4.1.x/bin/scAgent start
----


* 相关信息 *

xref:task_installing_the_snap_creator_agent_on_unix.adoc[在基于 UNIX 的系统上安装 Snap Creator 代理]
