---
permalink: installation/task_upgrading_snap_creator_server_4_1_x_on_windows.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, server, 4.1.x, windows 
summary: 您可以从 Windows 上的 Snap Creator Server 4.1.x 进行升级。 
---
= 在 Windows 上升级 Snap Creator Server 4.1.x
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从 Windows 上的 Snap Creator Server 4.1.x 进行升级。

* 在备份 Snap Creator 目录之前，您必须已停止 Snap Creator 服务（ `snapcreatorserverservice` 和 `snapcreatoragentservice` ），以确保备份的数据完整。
+
例如，您可以使用服务管理单元停止服务：

+
.. 选择 * 开始 * > * 运行 * 并输入 `services .msc` 。
.. 找到并选择 Snap Creator 服务，然后停止该服务。或者，您也可以打开命令提示符并输入以下命令：


+
[listing]
----
sc stop snapcreatorserverservice
sc stop snapcreatoragentservice
----
* 您必须已备份 Snap Creator 4.1.x Server 引擎子目录（ C ： \Program Files\NetApp\Snap_Creator_Frider\scServer4.1.x\engine ）中的以下目录以及所有关联的子目录和文件：
+
** Snap Creator 数据库（ .\snapcreator ）
** Snap Creator 服务器属性（ .\etc ）
** 配置文件（ .\configs ）
** 日志（ .\logs ）
** 插件存储库（如果已启用）（ .\snapcreatorPlugin ）


* （可选）如果 Snap Creator 代理与 Snap Creator 服务器安装在同一主机上，则应备份 Snap Creator 代理目录（ C ： \Program Files\NetApp\Snap_Creator_Frider\scAgent4.1.x ）中的以下目录以及所有关联的子目录和文件：
+
** Snap Creator Agent 属性（ .\etc ），其中包含 allowed_commands.config 和 agent.properties 文件
** 日志（ .\logs ）
** 插件（ .\plugins ）


* 如果 Snap Creator 是从命令提示符手动启动的，则必须关闭命令提示符并将其停止。
+

NOTE: 如果 Snap Creator 是从某个服务启动的，则卸载程序会在卸载过程中停止该服务。



以下步骤中提供的路径是指 Windows 的默认安装路径。如果未使用默认值，则路径信息可能与安装路径不同。

升级过程完成后，请考虑以下问题：

* 如果升级的 Snap Creator 数据库包含一些标记为 "`in progress` " 的任务，则即使升级过程完成，此状态也会保持不变。
* 最新版本的 Snap Creator 中的默认管理员必须是 Snap Creator 4.1 中的管理员。
+
如果 4.1.x 用户不是管理员，则升级会为 4.1.x 用户分配操作员角色。

+
.. 如果尚未停止 Snap Creator 服务，请停止此服务。
+
有关停止服务的信息，请参阅本主题前面提供的详细信息。

.. 选择 * 开始 * > * 程序 * > * Snap Creator* > * 卸载 NetApp Snap Creator Framework * ，卸载 Snap Creator （适用于 Windows ）。
+
有关详细信息，请参见有关在 Windows 上卸载 Snap Creator 的信息。

.. 安装最新的 Snap Creator 服务器。
+
有关详细信息，请参见有关在 Windows 上安装 Snap Creator 服务器的信息。

.. 如果在安装最新的 Snap Creator 服务器时选择以服务的形式启动 Snap Creator 服务器，请停止此服务。
+
有关停止服务的信息，请参阅本主题前面提供的详细信息。

.. 删除 C ： \Program Files\NetApp\Snap_Creator_Fridation\scServer4.1.x\enginer\snapcreator 中最新的 Snap Creator Server 数据库文件夹。
.. 将备份的 Snap Creator 4.1 数据库目录复制到以下位置的最新位置： C ： \Program Files\NetApp\Snap_Creator_Frider\scServer4.1.x\enginer\snapcreator ）。
.. 将备份的 Snap Creator 4.1 配置目录复制到以下位置的最新位置： C ： \Program Files\NetApp\Snap_Creator_Fridation\scServer4.1.x\enginer\configs ）。
.. 将备份的 Snap Creator 4.1 日志目录复制到以下位置的最新位置： C ： \Program Files\NetApp\Snap_Creator_Fridation\scServer4.1.x\enginer\logs ）。
.. 打开命令提示符并将目录更改为 Snap Creator 安装路径中的 engine 子目录，其位置为 C ： \Program Files\NetApp\Snap_Creator_Frider\scServer4.1.x\engine ）。
.. 输入以下命令以升级 Snap Creator ： java -JAR snapcreator.jar -upgrade




升级过程完成后，通过执行以下操作之一启动 Snap Creator 服务器服务：

* 使用服务管理单元并启动服务。
* 在命令提示符处，输入以下命令：
+
[listing]
----
sc start snapcreatorserverservice
----


此外，您还必须通过导航到指定端口上的本地主机来验证 Snap Creator Framework 图形用户界面的启动情况 。

您必须使用 HTTPS 进行连接；否则，此连接不会自动重定向到 HTTPS 连接，并且图形用户界面将不起作用。
