---
permalink: installation/task_upgrading_snap_creator_server_4_1_x_on_unix_based_systems.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, server, 4.1.x, unix, unix-based 
summary: 您可以在基于 UNIX 的系统上从 Snap Creator Server 4.1.x 进行升级。 
---
= 在基于 UNIX 的系统上升级 Snap Creator Server 4.1.x
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在基于 UNIX 的系统上从 Snap Creator Server 4.1.x 进行升级。

* 在备份 Snap Creator 目录之前，您已停止 Snap Creator 进程，以确保备份的数据完整。
+
例如，输入以下命令：

+
[listing]
----
/install_path/scServer4.1.0/bin/scServer stop
/install_path/scAgent4.1.0/bin/scAgent stop
----
* 您已在 Snap Creator 4.1.x Server 引擎子目录（ /install_path/scServer4.1.x 引擎）中备份以下目录以及所有关联的子目录和文件：
+
** Snap Creator 数据库（ ./snapcreator ）
** Snap Creator 服务器属性（ ... 等）
** 配置文件（ ./configs ）
** 日志（ ./logs ）
** 插件存储库（如果已启用）（ ./snapcreatorPlugin ） * 注意： * 您不能删除已创建的 Snap Creator 4.1.x 备份副本。




以下步骤中提供的路径是指默认安装路径。如果未使用默认值，则路径信息可能与安装路径不同。

升级过程完成后，您应考虑以下问题：

* 如果升级的 Snap Creator 数据库包含一些标记为 "`in progress` " 的任务，则即使升级过程完成，此状态也会保持不变。
* 最新版本的 Snap Creator 中的默认管理员必须是 Snap Creator 4.1.x 中的管理员
+
如果 4.1.x 用户不是管理员，则升级会为 4.1.x 用户分配操作员角色。

+
.. 如果尚未停止 Snap Creator 进程，请执行此操作。
+
有关停止进程的信息，请参阅本主题前面提供的详细信息。

.. 安装最新版本的 Snap Creator ，但不要启动 Snap Creator 服务器。
+
有关详细信息，请参见有关在 UNIX 上安装 Snap Creator 服务器的信息。

.. 将备份的 Snap Creator 4.1.x 数据库目录复制到 /install_path/scServer4.1.x/enginer/snapcreator 的最新位置。
.. 将备份的 4.1.x 配置目录复制到 /install_path/scServer4.1.x/enginer/configs 的最新位置。
.. 将备份的 4.1.x 日志目录复制到 /install_path/scServer4.1.x/enginer/logs 的最新位置。
.. 将目录更改为 Snap Creator 安装路径中的 engine 子目录，其位置为 /install_path/scServer4.1.x/engine 。
.. 输入以下命令以升级 Snap Creator ： java -JAR snapcreator.jar -upgrade




升级过程完成后，输入以下命令启动 Snap Creator Server ：

[listing]
----
/install_path/scServer4.1.x/bin/scServer start
----
此外，还应删除 Snap Creator 4.1.x 安装目录。


IMPORTANT: 在确定不需要还原到旧版本之前，请勿删除备份副本。

此外，您还必须导航到指定端口上的本地主机来验证 Snap Creator Framework 图形用户界面的启动情况 (https://IP_address:gui_port)[]。

您必须使用 HTTPS 进行连接；否则，此连接不会自动重定向到 HTTPS 连接，并且图形用户界面将不起作用。
