---
permalink: installation/task_uninstalling_snap_creator_on_windows.html 
sidebar: sidebar 
keywords: uninstalling, uninstall, snap, creator, windows 
summary: 您可以使用 Windows 的 " 开始 " 菜单卸载 Snap Creator 。Windows 卸载程序会删除已安装的 Snap Creator 组件 \ （例如，如果同时安装了 Snap Creator Server 和 Snap Creator Agent ，则两者都将被卸载 \ ）。同样，如果仅安装了其中一个组件，则该组件将被卸载。 
---
= 在 Windows 上卸载 Snap Creator
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Windows * 开始 * 菜单卸载 Snap Creator 。Windows 卸载程序会删除已安装的 Snap Creator 组件（例如，如果同时安装了 Snap Creator Server 和 Snap Creator Agent ，则两者都将被卸载）。同样，如果仅安装了其中一个组件，则该组件将被卸载。

* 在 Snap Creator 服务器引擎目录（ C ： \Program Files\NetApp\Snap_Creator_Frider\scServer4.1.0\engine ）中备份以下目录以及所有关联的子目录和文件：
+
** Snap Creator 数据库（ .\snapcreator ）
** Snap Creator 服务器属性（ .\etc ）
** 配置文件（ .\configs ）
** 日志（ .\logs ）
** 插件存储库（如果已启用）（ .\snapcreatorPlugin ）


* 备份 Snap Creator Agent 目录（ C ： \Program Files\NetApp\Snap_Creator_Frider\scAgent4.1.0 ）中的以下目录以及所有关联的子目录和文件：
+
** 日志（ .\logs ）
** 插件（ .\plugins ）
** Snap Creator Agent 属性（ .\etc ），其中包含 allowed_commands.config 和 agent.properties 文件


* 如果 Snap Creator 是从命令提示符手动启动的，请关闭命令提示符以停止并退出 Snap Creator 。
+

NOTE: 如果 Snap Creator 是从某个服务启动的，则卸载程序会在卸载过程中停止该服务。

+
.. 选择 * 开始 * > * 所有程序 * > * Snap Creator* > * 卸载 NetApp Snap Creator Framework * 。
.. 在卸载 Snap Creator 之前，如果系统提示您是否备份了日志和配置文件，请单击 * 是 * 。
.. 卸载过程完成后，如果出现提示，请单击 * 关闭 * 。



